[[headers]]
  for = "https://mhw-db.com/*"
  [headers.values]
    access-control-allow-credentials = false
    access-control-allow-headers = "*"
    access-control-allow-methods = "*"
    access-control-allow-origin = "https://mhw-db.netlify.com"
[[headers]]
  for = "https://mhw-db.com/armor/*"
  [headers.values]
    access-control-allow-credentials = false
    access-control-allow-headers = "*"
    access-control-allow-methods = "*"
    access-control-allow-origin = "https://mhw-db.netlify.com"
[[headers]]
  for = "https://mhw-db.com/skills/*"
  [headers.values]
    access-control-allow-credentials = false
    access-control-allow-headers = "*"
    access-control-allow-methods = "*"
    access-control-allow-origin = "https://mhw-db.netlify.com"