[[headers]]
  for = "https://mhw-db.com/*"
  [headers.values]
    Access-Control-Allow-Origin =  "*"
[[headers]]
  for = "https://mhw-db.com/armor/*"
  [headers.values]
    Access-Control-Allow-Origin =  "*"
[[headers]]
  for = "https://mhw-db.com/skills/*"
  [headers.values]
    Access-Control-Allow-Origin =  "*"